import type { Bi } from "./i18n";

/** Extra close-in-the-field notes so each product page lands in the 600–900 word band. */
export const PRODUCT_NOTES: Record<string, { h2: Bi; paras: Bi[] }> = {
  "inflation-accounting": {
    h2: { tr: "Kapanış günü nasıl durur?", en: "What close day actually looks like" },
    paras: [
      {
        tr: "Kapanış sabahı endeks tablosu dündür. Biri ‘geçici endeksle çalıştıralım’ der; denetçi geçici sevmez. Paket, endeks versiyonunu belgede kilitler: geçici çalıştırma ayrı belge türüdür, kesin çalıştırma ayrı. İkisini aynı türde karıştırmak, sonraki ay ters kayıt avına çıkar. Duran varlıkta yıl içi alım, düzeltmenin hangi aydan başlayacağını değiştirir; ‘tüm varlıklar aynı endeks’ kolaycılığı mizanı kaydırır. Stokta dönem kapanmadan miktar hareketi varsa düzeltme miktarı değil, değerleme farkını konuşursunuz — MM ve FI aynı rapora bakmadan ‘stok tutmadı’ demeyin. Özkaynak düzeltmesi dipnota gider; yönetim bunu ‘zarar’ sanmasın diye kâr merkezi raporu ayrı anlatılır. Eğitim, program tuşu değil, hesap sınıfı ve belge türü üzerinedir. AMS takviminde endeks günü, kapanıştan iki gün önce durur. O gün bilet kuyruğuna düşerse kapanış kahramanlık ister; kahramanlık süreç değildir. İlk yıl, sınıflama hataları çıkar: parasal sanılan avans, parasal olmayan çıkar. Bunu utanılacak bir keşif değil, temizlik kabul edin. İkinci yıl çalıştırma sıkıcı olmalıdır. Sıkıcı, doğru işaretidir. Conforcus bu paketi ‘enflasyonu bitirdik’ slaytı için yazmaz; sizin tebliğ takviminiz için yazar. Rakam uydurmayız. Sizin mizanınız konuşur.",
        en: "On close morning the index table is yesterday’s. Someone says ‘run on a provisional index’; auditors dislike provisional. The package locks the index version on the document: a provisional run is one document type, a final run another. Mix them and next month is a reversal hunt. In-year asset acquisitions change from which month restatement starts; ‘all assets, one index’ is how the trial balance slides. If inventory still moves before period-end you are talking valuation difference, not quantity — do not say ‘stock does not tie’ until MM and FI read the same report. Equity restatement goes to the notes; tell management it is not ‘a loss’ in the P&L they stare at. Training is not the program button; it is account class and document type. On the AMS calendar, index day sits two days before close. If it falls into the ticket pile, close needs heroes, and heroes are not a process. Year one, classification errors appear: an advance you thought monetary is not. Treat that as cleaning, not shame. Year two the run should be boring. Boring is the signal. We do not ship this package for an ‘inflation is done’ slide; we ship it for your gazette calendar. We invent no figures. Your trial balance speaks.",
      },
      {
        tr: "Sık sorulan bir kısayol vardır: ‘geçen yılın Excel’ini birkere yükleyelim’. Yüklemek, sınıfı doğrulamak değildir. Açılış bakiyesi düzeltmesi yanlışsa her sonraki çalıştırma o yanlışı çoğaltır. Bu yüzden ilk kurulumda geçmiş yıl köprüsü ayrı bir kabul kriteridir. Kabul, ‘program hata vermedi’ değildir; seçilmiş hesapların elle hesaplanmış örnekle farkı açıklanabilir olmaktır. Örnek üç hesaptır, kırk sekiz değil — ama o üç hesap duran varlık, stok ve parasal kalemden seçilir. Böylece modelin üç kası da gerilir. Holding’de şirket kodları farklı para birimi ve farklı enflasyon ortamındaysa tek program-tüm-grup hayali kırılır. Şablon kuraldır, endeks yereldir. Rollout cümlesi budur.",
        en: "There is a popular shortcut: ‘just load last year’s Excel once’. Loading is not validating class. If the opening restatement is wrong, every later run multiplies it. So the prior-year bridge is its own acceptance criterion on first install. Acceptance is not ‘the program did not dump’; it is that a handful of accounts can be explained against a hand calculation. Three accounts, not forty-eight — but those three are chosen from PPE, inventory and a monetary item, so all three muscles of the model flex. In a holding with different currencies and inflation settings, the fantasy of one program for the whole group breaks. The rule is template; the index is local. That is the rollout sentence.",
      },
    ],
  },
  "e-payment-bank-e-signature-integrations": {
    h2: { tr: "Ödeme sabahı ve sahte acil", en: "Payment morning and fake urgency" },
    paras: [
      {
        tr: "Ödeme sabahı her zaman acildir. Acil olan, imza kuyruğunun görünmesidir; dosyayı USB ile taşımak değil. Banka kesintisi, sertifika dolumu ve yanlış IBAN üç ayrı arızadır; hepsine ‘sistem yok’ denmesi AMS’i körleştirir. Paket, hata kodunu ödeme belgesine yazar. Hazine, banka operasyonu ve FI aynı kuyruğa bakar. Çift imza, ‘iki kişi mail attı’ değildir; BCM veya eşdeğer kademedir. Tedarikçi master’ında banka hesabı değişince ödeme önerisi eski hesabı kullanırsa bu bir master data olayıdır, entegrasyon sucu değil — ama entegrasyon, değişikliği öneri anında gösterir. Yurtdışı ödeme (döviz, muhabir banka) ayrı payment medium ister. ‘Hepsi XML’ diye tek dosyaya tıkmak, iade ve kesinti mesajını okunamaz kılar. Türkiye e-ödeme ürünleri bankadan bankaya değişir; keşif günü banka listesi ve imza politikası masaya gelir, slayt değil. İlk ay yalnızca bir şirket kodu ve bir banka ile canlıya alın, ikinci bankayı ikinci aya bırakın. İki bankayı aynı sabah açmak, hangi ucun kırıldığını gizler. Güvenlik ekibi IP ve sertifikayı, finans rolü onay kademesini sahiplenir. Karışırsa her kesinti ‘IT’ biletidir. Değildir.",
        en: "Payment morning is always urgent. The urgency is seeing the signature queue, not walking a file on a stick. Bank outage, expired certificate and wrong IBAN are three faults; calling all of them ‘the system is down’ blinds AMS. The package writes the error on the payment document. Treasury, bank ops and FI read one queue. Dual signature is not ‘two people mailed’; it is BCM or an equivalent step. If a vendor bank account changes and the proposal still uses the old one, that is master data, not ‘the interface’ — but the interface must surface the change at proposal time. Cross-border payments (FX, correspondent) want their own payment medium. Jamming everything into one XML makes returns unreadable. Türkiye e-payment products differ by bank; discovery puts the bank list and signature policy on the table, not on a slide. Month one, one company code and one bank live; the second bank waits. Opening two banks the same morning hides which edge broke. Security owns IP and certificates; finance owns approval steps. Mix them and every outage is an ‘IT’ ticket. It is not.",
      },
      {
        tr: "Dolandırıcılık senaryosu (tedarikçi hesabı değişimi) süreçte bir onay adımı ister: master değişikliği ile ödeme aynı gün aynı kişide birleşmesin. Bu cümle yazılım özelliği değil, kontrol tasarımıdır; paket adımı taşır, politikayı siz yazarsınız. Banka teyidi gelmeden açık kalemi kapatmak nakit raporunu yalanlar. Teyit gecikirse kalem ‘yolda’ durumunda bekler. Kapanışta ‘yolda’ listesi hazine’nin listedir, mali işlerin utancı değil. Utanç, listenin olmamasıdır.",
        en: "A fraud scenario (vendor account change) wants a control step: master change and payment must not meet in the same person the same day. That is control design, not a ‘feature’; the package carries the step, you write the policy. Clearing the open item before the bank acknowledges lies to the cash report. If the ack is late, the item waits in ‘in flight’. At close, ‘in flight’ is treasury’s list, not finance’s shame. Shame is not having the list.",
      },
    ],
  },
  "customer-vendor-e-reconciliation": {
    h2: { tr: "Ayın 5’i ve sessizlik", en: "The 5th of the month and silence" },
    paras: [
      {
        tr: "Mutabakatın düşmanı fark değil, sessizliktir. Gönderilmeyen cari, ‘sorun yok’ sanılır. Paket, gönderilmemişi kırmızıya boyar. Teyit, ihtilaf ve sessizlik üç ayrı koddur; yüzde uydurmayız, adet sayarız. Büyük tedarikçiler portal ister, küçükler e-posta. İkisini aynı SLA ile dövmek haksızdır. Dil ve antet şirket koduna göredir; holding İngilizce gönderir diye Türkiye carisi anlamaz. Açık kalem eklemek yazışmayı uzatır ama ihtilafı kısaltır — çünkü farkın hangi belgede olduğu konuşulur. Kişisel e-posta kuyruğu KVKK ve iş sürekliliği riskidir; iş hesabı ve vekâlet yazılır. İlk mutabakat ayı öğrenme ayıdır: yanlış bakiye giden üç cari, master data temizliğidir. Utanılacak bir go-live hatası değil, beklenen tozdur. İkinci ay, sessiz kalanlara telefon script’i değil, sistemdeki ikinci gönderimdir. Üçüncü ay, kapanış komitesi ‘teyit adedi’ne bakar. Bu bir skor tahtası değil, kuyruk sağlığıdır. Conforcus, ‘mutabakat bitti’ demez; kuyruk görünür der.",
        en: "Reconciliation’s enemy is not difference; it is silence. An account not sent is mistaken for ‘no issue’. The package paints unsent red. Confirmed, disputed and silent are three codes; we do not invent a percentage, we count. Large vendors want a portal, small ones mail. Beating both with one SLA is unfair. Language and letterhead follow company code; a holding sending English does not make a Turkish account understand. Adding open items lengthens the letter and shortens the dispute — because you talk about which document. Personal mailboxes are KVKK and continuity risk; a work account and a deputy are written down. Month one is learning: three accounts that got the wrong balance are master-data cleaning. Not a shameful go-live bug — expected dust. Month two, silence gets a second send in the system, not a phone script. Month three, the close committee looks at confirm counts. That is queue health, not a scoreboard. We do not say ‘reconciliation is done’; we say the queue is visible.",
      },
      {
        tr: "S4 BP’ye geçişte müşteri ve satıcı birleşince aynı BP’ye iki bakiye gitmemesi için gönderim hesabı tipi seçilir. ECC’de bu sorun ayrı master ile gizlenirdi. Dönüşüm projesi mutabakatı ‘sonraya’ bırakırsa go-live sonrası ilk ay mektuplar karışır. Bu yüzden S/4 programında mutabakat, finans veri dönüşümünün komşusudur — 2. faz değil.",
        en: "On S/4 BP, customer and vendor merge: you choose which account type you send so one BP does not get two balances. ECC hid this with two masters. If a transformation parks reconciliation as ‘later’, month one after go-live mixes the letters. That is why reconciliation sits next to finance data conversion on an S/4 programme — not phase 2.",
      },
    ],
  },
  "ifrs-16-package": {
    h2: { tr: "Sözleşme çekmecesi ve dipnot", en: "The contract drawer and the note" },
    paras: [
      {
        tr: "IFRS 16’nın yarısı muhasebe, yarısı envanterdir. Çekmecede duran kira, sistemde yoksa dipnot yalan söyler. Paket, ‘sözleşme yoksa kayıt yok’ disiplinini dayatmaz; eksik sözleşmeyi kuyruğa yazar. Kuyruk, kiralama ekibinin işidir. Erken fesih ve kapsam değişikliği, eski nakit akışını ezer; bunu Excel’de satır silerek yapmak faiz ve varlık bakiyesini bırakır. SAP’de değişiklik belgesi, eski hesaplamanın izini saklar. Araç kirası ile gayrimenkul aynı iskonto hikâyesini paylaşmaz; politika bunu ayırır. Kısa vadeli istisna ‘12 ay’ diye ezberlenir, yenileme opsiyonu unutulur. Opsiyon iş kararıdır, yazılım kararı değil; alan işaretlenir, yorum hukukta kalır. Ay sonu: faiz, amortisman, kira ödemesi. Üçü aynı gün, üç belge, üç kontrol listesi. Biri unutulursa dipnot ‘neredeyse’ tutar — denetçi neredeyse sevmez. AMS, yeni sözleşme girişini ‘proje talebi’ sanmasın diye self-service bir ekran ve kısa eğitim veririz. Eğitim, standardın teorisi değil, sizin eşiklerinizdir.",
        en: "Half of IFRS 16 is accounting; half is inventory. A lease in a drawer that is not in the system makes the note a lie. The package does not refuse to post; it queues the missing contract. That queue is the lease team’s job. Early termination and scope change overwrite old cash flows; deleting a spreadsheet row leaves interest and the RoU behind. In SAP a modification document keeps the old calculation’s trail. Vehicle leases and property do not share a discount story; policy splits them. The short-term exemption is memorised as ‘12 months’ and the renewal option is forgotten. The option is a business call, not software; a field is flagged, interpretation stays with legal. Month-end: interest, depreciation, lease payment. Three on the same day, three documents, three checks. Skip one and the note ‘almost’ ties — auditors dislike almost. AMS should not treat a new contract as a project request; we give a self-service screen and a short training. Training is not the standard’s theory; it is your thresholds.",
      },
      {
        tr: "Yerel defter kira giderini nakden görmek isteyebilir; IFRS varlık ve faiz görür. İki hikâye, iki defter. Tek slaytta birleştirmek CFO’yu yalnız bırakır. Paket raporları ayırır. Global rollout’ta ülke kira hukuku ‘şablonu bozma’ gerekçesi değildir; lokal alan şablona eklenir. Almanya veya başka bir ülke, Türkiye kira teamülünü taşımaz. Bunu Flormar Almanya kickoff’undaki DATEV/e-fatura cümlesiyle karıştırmayın — o başka bir programın lokalizasyonudur. Bu paket kira muhasebesidir.",
        en: "The local book may want to see cash rent; IFRS sees an asset and interest. Two stories, two books. Merging them on one slide leaves the CFO alone. The package splits the reports. In a rollout, local lease law is not a reason to smash the template; local fields are added. Germany — or anywhere else — does not carry Turkish lease habit. Do not mix this with DATEV/e-invoicing sentences from a Germany rollout kickoff; that is another programme’s localization. This package is lease accounting.",
      },
    ],
  },
  "direct-debit-system-dbs-bank-integration": {
    h2: { tr: "Ret kodu ve satışın haberi", en: "Reject codes and when sales hears" },
    paras: [
      {
        tr: "DBS reddi, tahsilatın değil ilişkinin sinyalidir: limit, hesap, iptal, bakiye. Satış bunu haftalar sonra duyarsa yeni sevk yola çıkar. Paket ret kodunu açık kaleme ve isteğe bağlı kredi uyarısına yazar. Uyarı, blok değildir. Blok, kredi politikasıdır. Banka dosyası kesilince ‘ödeme gelmedi’ sanılır; aslında talimat gitmemiştir. İz, dosya numarası ve saat damgasıdır. Mükerrer talimat, mükerrer tahsilat riskidir; açık kalem kilidi ikinci dosyayı durdurur. Bayi ağı olan üreticide DBS, nakit kültürünün parçasıdır. Kültürü yazılım değiştirmez; görünür kılar. İlk canlı ay tek banka, düşük hacimli bir müşteri grubu. Tüm ciroyu birinci salı bankaya sürmek, kesintiyi felakete çevirir. Sözlük (ret kodları) banka değişince güncellenir. Güncellenmezse kuyruk ‘diğer’ ile dolar ve kimse okumaz. AMS bunu kapanıştan bağımsız küçük bir ritüel yapar. Ritüel yoksa her ay yeniden keşif yapılır. Keşif pahalıdır, ritüel ucuzdur.",
        en: "A DBS reject is a relationship signal, not only a collections signal: limit, account, cancel, balance. If sales hears weeks later, another shipment leaves. The package writes the code on the open item and optionally onto a credit warning. A warning is not a block. A block is credit policy. When the bank file is cut, people say ‘payment did not arrive’; actually the instruction never left. The trail is a file number and a timestamp. A duplicate instruction is duplicate collection risk; the open-item lock stops the second file. For a manufacturer with dealers, DBS is part of cash culture. Software does not change culture; it makes it visible. First live month: one bank, a small customer group. Pushing all revenue at the bank on the first Tuesday turns an outage into a disaster. The reject dictionary updates when the bank changes. If it does not, the queue fills with ‘other’ and nobody reads. AMS makes that a small ritual independent of close. No ritual, and every month is discovery again. Discovery is expensive; ritual is cheap.",
      },
      {
        tr: "Müşteri talimatının hukuki varlığı banka ve sözleşme dosyanızdadır. SAP bir işaret tutar. İşareti yanlış açmak, istemeyen cariden para çekmeye teşebbüstür. Önizleme ve çift onay burada ‘bürokrasi’ değil, durdurucudur. KVKK metnimiz geneldir; DBS müşteri listesi işleme amacı tahsilattır, pazarlama değildir. Bu ayrım süreçte yazılı durur.",
        en: "The legal mandate lives in the bank and your contract file. SAP holds a flag. Opening the flag wrong is an attempt to pull money from an account that did not ask. Preview and dual approval are brakes, not bureaucracy. Our KVKK notice is general; the purpose of a DBS customer list is collection, not marketing. That split is written in the process.",
      },
    ],
  },
  "automated-clearing-processes": {
    h2: { tr: "Kuralın sıkıcılığı", en: "The boredom of a good rule" },
    paras: [
      {
        tr: "İyi denkleştirme kuralı sıkıcıdır. Heyecan, kuyruktadır. Kuyrukta kur farkı, kısmi ödeme, yanlış referans ve sahte çift kayıt durur. Hepsini otomatik kapatmak, mizanı ‘düzgün’ gösterir, cariyi yalanlar. Paket, heyecanı kuyrukta bırakır. Haftalık bakış: düşen örnekler. Örnek, suçlama değil, kuralın bir sonraki cümlesidir. Referans disiplinini satış ve satın alma bozar; FI tek başına düzeltmez. Bu yüzden keşifte üç ekip vardır. F.13 çalışan bir şirkette paket, F.13’ü rafa kaldırmak zorunda değildir; sizin açıklama kalıplarınızı ekler. S/4’te banka entegrasyonu (lockbox, camt) kuralın girdi kalitesini yükseltir. Girdi çöpse otomasyon çöpü hızlandırır. Önce master ve ödeme açıklaması, sonra kural. Tersine sıra, ‘otomasyon işe yaramadı’ efsanesini doğurur. Efsane yanlıştır: çöp hızlanmıştır. AMS, yeni banka açıklama kalıbını kurala eklemeyi proje sanmaz. İki satırlık bir bakımdır. Bakım yapılmazsa insanlar tekrar satır tıklamaya döner ve paket ‘ölmüş’ ilan edilir. Ölmemiştir; bakılmamıştır.",
        en: "A good clearing rule is boring. Excitement lives in the queue. The queue holds FX, partials, bad references and fake duplicates. Auto-closing all of them makes the trial balance look tidy and the subledger a lie. The package leaves excitement in the queue. Weekly: samples of drops. A sample is the next sentence of the rule, not a prosecution. Sales and procurement break reference discipline; FI cannot fix that alone. So discovery has three teams. If F.13 already runs, the package does not have to shelf it; it adds your text patterns. In S/4, bank integration (lockbox, camt) raises input quality. Garbage in, automation speeds garbage. Master and payment text first, rule second. Reverse that order and you birth the myth that ‘automation did not work’. The myth is wrong: garbage got faster. AMS does not treat a new bank-text pattern as a project. It is two lines of care. Skip care and people click lines again and declare the package dead. It is not dead; it is unattended.",
      },
      {
        tr: "Kısmi denkleştirme, nakit iskontosu ve kur farkı aynı ekranda konuşulursa kural şişer ve kimse okumaz. Ayırın: önce bire bir, sonra tolerans, sonra iskonto hesabı. Okunmayan kural, yazılı olmayan kuraldır. Denetçi okunmayan kuralı kontrol saymaz.",
        en: "If partials, cash discount and FX share one screen, the rule bloats and nobody reads it. Split: exact first, tolerance second, discount account third. An unread rule is an unwritten rule. Auditors do not count unread rules as control.",
      },
    ],
  },
  "import-management-process": {
    h2: { tr: "Dosya kapanmadan satış fiyatı", en: "Selling before the file closes" },
    paras: [
      {
        tr: "İthal mal yola çıkmadan satış fiyatı konuşulur. Konuşulur, çünkü pazar bekler. Stok değeri henüz navlunu içermiyorsa marj yalan söyler. Paket, planlı masrafı girişte yükler; gerçek fatura gelince farkı aynı kurala bağlar. Bu, ‘tahmini tutturduk’ iddiası değildir; farkı görünür kılar. Gümrükte bekleyen mal, stokta ‘var’ görünürse üretim planı şaşar. Durum kodu (yolda / gümrük / açık) MRP’ye kadar gitmek zorunda değildir; en azından satın alma ve finans aynı kodu görür. Antrepo ve teminat, nakit çıkışıdır; dosyaya bağlanmazsa hazine ‘neden çıktı’ diye sorar. Bağlanır. GTIP değişince tarife değişir; eski sipariş satırı yeni tarifeyi sessizce almamalıdır — çelişki raporu. Müşavir Excel’i durabilir. Dursun. Sizin kapanışınız belgeden okunur. İlk dosya canlıya alınırken tek tedarikçi, tek rejim. On rejim, birinci hafta, hangisinin kırıldığını gizler. AMS: yeni masraf taşıyıcısı (ör. yerli nakliye), yeni vergi kodu, kur tipi. Bunlar proje talebi değildir. Proje, yeni bir ülke gümrüğüdür. Karıştırmayın.",
        en: "Sales price is discussed before the goods leave. It is discussed because the market waits. If stock value does not yet include freight, margin lies. The package loads planned cost at GR; the actual invoice then follows the same rule. That is not a claim we ‘hit the estimate’; it makes the difference visible. Goods waiting at customs that look ‘in stock’ break production plans. Status (in transit / customs / open) does not have to reach MRP; at least procurement and finance see the same code. Bonded warehouse and guarantees are cash out; if they are not on the file, treasury asks ‘why did this leave’. They are bound. When HS code changes, tariff changes; an old PO line must not silently pick up the new tariff — conflict report. The broker spreadsheet may stay. Let it. Your close reads from a document. First live file: one vendor, one regime. Ten regimes in week one hide which one broke. AMS: a new cost carrier (domestic trucking), a new tax code, a rate type. Those are not project requests. A project is a new country’s customs. Do not mix them.",
      },
      {
        tr: "Incoterms alanı boşsa herkes CIF varsayar. Varsayım, stok değeridir. Zorunlu alan ve sipariş onayı, ithalat paketinin ‘gümrük özelliği’ değil, MM disiplinidir. Paket disiplini hatırlatır, satın almanın yerine geçmez.",
        en: "If Incoterms is blank, everyone assumes CIF. The assumption is stock value. A mandatory field and PO approval are MM discipline, not a ‘customs feature’. The package reminds; it does not replace procurement.",
      },
    ],
  },
  "invoice-approval-workflow": {
    h2: { tr: "Park listesi ve tatil", en: "The park list and holiday" },
    paras: [
      {
        tr: "Onaycı tatile çıkar. Vekâlet yoksa fatura dönemde kalır, KDV sapar, tedarikçi arar. Vekâlet, org şemasında bir satırdır; yazılı değilse yoktur. Paket, süre aşımında vekile düşer. Düşmezse kapanış listesi şişer. E-fatura yasal reddi ayrı bir saattir; iç onay ayrı. İkisini karıştırmak ya yasal süreyi yakar ya da her faturayı panikle reddettirir. Üç yollu sapmada ‘fiyat farkı’ ile ‘hiç giriş yok’ aynı kuyrukta durmamalıdır. İlki tolerans, ikincisi depo. Karışınca herkes her şeyi imzalar. İmza sirküleri tutar eşiğini yazılı verir; yazılım yuvarlak eşik uydurmaz. İlk ay, park süresi dağılımına bakılır — skor değil, kuyruk yaşlanması. Yaşlanan fatura, süreç hatasıdır, kullanıcı tembelliği değil (çoğu kez vekâlet ve eşik). Fiori, onaycıyı GUI’ye mahkûm etmemek içindir. Mali işler parkı GUI’de izleyebilir. İki arayüz, iki rol. Confiq Scan ve analiz formu, ‘fatura onayımız yok’ diyen ekipler için kapıdır; bu sayfa paketin ne olduğunu anlatır, sihir vaadetmez.",
        en: "The approver goes on holiday. Without a deputy the invoice misses the period, VAT drifts, the vendor calls. A deputy is a line in the org chart; if it is unwritten it does not exist. The package falls to the deputy on timeout. If it does not, the close list grows. The statutory e-invoice reject window is one clock; internal approval is another. Mix them and you either burn the legal window or panic-reject everything. In three-way mismatch, ‘price difference’ and ‘no GR’ must not share a queue. One is tolerance, the other is the warehouse. Mix them and everyone signs everything. The signature circular writes amount thresholds; software does not invent round numbers. Month one, look at park-age distribution — queue ageing, not a score. An ageing invoice is usually a process miss (deputy, threshold), not lazy users. Fiori exists so approvers are not trapped in GUI. Finance can still watch the park list in GUI. Two UIs, two roles. Confiq Scan and the analysis form are the door for teams who say ‘we have no invoice approval’; this page says what the package is. It does not promise magic.",
      },
      {
        tr: "Siparişsiz gider faturasında maliyet nesnesi boşsa onay, ‘kimin bütçesi’ sorusunu sonraya bırakır. Sonra, kapanıştır. Zorunlu maliyet nesnesi, bürokrasi değil, bütçe paketinin komşusudur. FM/PS kullananlarda onay, bütçe kontrolü ile çelişmesin diye keşifte konuşulur. Çelişki, canlıda sürpriz olmasın.",
        en: "On a non-PO expense, an empty cost object postpones ‘whose budget’. Later is close. A mandatory cost object is a neighbour of the budget package, not bureaucracy. Where FM/PS is live, discovery asks that approval not fight budget control. The fight should not be a production surprise.",
      },
    ],
  },
};
