import { defineArrayMember, defineField, defineType } from "sanity";
import { portableText } from "./objects";

export default defineType({
  name: "solution",
  title: "Solution / Çözüm",
  type: "document",
  fields: [
    defineField({ name: "name_tr", title: "Name (TR) / Ad", type: "string", validation: (r) => r.required() }),
    defineField({ name: "name_en", title: "Name (EN)", type: "string", validation: (r) => r.required() }),
    defineField({
      name: "module",
      title: "Module / Modül",
      type: "string",
      options: { list: ["FI", "CO", "MM", "SD", "PS", "FM", { title: "E-Çözümler (e-Dönüşüm)", value: "E" }] },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "group",
      title: "Group / Grup",
      type: "string",
      options: { list: [{ title: "Finans", value: "fin" }, { title: "Lojistik", value: "log" }, { title: "E-Çözümler", value: "edon" }] },
      validation: (r) => r.required(),
    }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "name_en", maxLength: 96 } }),
    defineField({ name: "short_tr", title: "Short (TR) / Kısa açıklama", type: "text", rows: 2 }),
    defineField({ name: "short_en", title: "Short (EN)", type: "text", rows: 2 }),
    defineField({ name: "body_tr", title: "Body (TR) / Detay", type: "array", of: portableText }),
    defineField({ name: "body_en", title: "Body (EN)", type: "array", of: portableText }),
    defineField({
      name: "benefits_tr",
      title: "Benefits (TR) / Kazanımlar",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      description: "3–5 kısa madde. Detay sayfasında \"Kazanımlar\" listesi olarak görünür; arama sonucu açıklamasını da besler.",
    }),
    defineField({ name: "benefits_en", title: "Benefits (EN)", type: "array", of: [defineArrayMember({ type: "string" })] }),
    defineField({
      name: "technical_tr",
      title: "Technical scope (TR) / Teknik kapsam",
      type: "text",
      rows: 3,
      description: "Çözümün SAP'ta hangi modül ve nesnelere oturduğu. Detay sayfasında \"SAP'ta nereye oturur\" başlığıyla görünür.",
    }),
    defineField({ name: "technical_en", title: "Technical scope (EN)", type: "text", rows: 3 }),
    defineField({ name: "audience_tr", title: "Audience (TR) / Kimler için", type: "string", description: "Örn. CFO, Finans Müdürü, Muhasebe & Hazine" }),
    defineField({ name: "audience_en", title: "Audience (EN)", type: "string" }),
    defineField({ name: "faqs", title: "FAQ", type: "array", of: [{ type: "faqItem" }] }),
    defineField({
      name: "references",
      title: "Bu çözümü kullanan referanslar",
      type: "array",
      of: [defineArrayMember({ type: "reference", to: [{ type: "clientReference" }] })],
      description: "Çözüm detay sayfasında logolarıyla listelenir.",
    }),
    defineField({ name: "featured", title: "Featured / Ana sayfa tabında göster", type: "boolean", initialValue: false }),
    defineField({ name: "order", title: "Order / Sıra", type: "number" }),
    defineField({ name: "seo", title: "SEO", type: "seo" }),
  ],
  orderings: [{ title: "Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: { select: { title: "name_tr", subtitle: "module" } },
});
